### ISSUE TITLE
Wrażenia

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [kwisniowski/MagicNumbers#1]
Heja!

1. Nie ma Mavena
2. Program jak się skompiluje, to się nie odpala (efekt poniżej)
3. Program nie pozwala na przetestowanie na moich plikach.
4. Strasznie imperatywnie: domyślny pakiet, 3 klasy zaledwie, kilkanaście if-else'ów w validate itp. itd. Poproszę o bardziej obiektową wersję.

```
java.io.FileNotFoundException: files\button.jpg (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at FileDifferentiator.validateJPGByMagicNumbers(FileDifferentiator.java:53)
	at FileDifferentiator.validateFile(FileDifferentiator.java:99)
	at Main.main(Main.java:19)
Exception in thread "main" java.io.FileNotFoundException: files\button.jpg (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at FileDifferentiator.validateGifByMagicNumbers(FileDifferentiator.java:41)
	at FileDifferentiator.validateFile(FileDifferentiator.java:102)
	at Main.main(Main.java:19)
```

**Comment by kwisniowski** [comment]
Cześć, 
Dziękuję za uwagi. Poniżej link do repozytorium z nową wersją. 
https://github.com/kwisniowski/magicNumbers2

Pozdrawiam!
